service: im-bcm-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
 - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
