service: im-bcm-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
 - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

custom:
  serverless-offline:
    lambdaPort: 3200
    port: 3000
    host: "127.0.0.1"
